name: Conda Package

on:
  pull_request:
    branches: '**'
  push:
    branches:
      - master

jobs:
  publish:
    name: Build and publish Conda distributions ðŸ“¦
    runs-on: Ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install and run DepHell
      uses: dephell/dephell_action@master
    - name: Export package version and name
      run: |
        export OPENROUTESERVICE_NAME=$(python setup.py --name)
        export OPENROUTESERVICE_VERSION=$(python setup.py --version)
    - name: publish-to-conda
      uses: MichaelsJP/conda-package-publish-action@v1.0.0
      with:
        subDir: 'conda.recipe'
        AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
        platforms: 'all'
        override: true
